name: Shared SFDO-Tooling Docs Review Workflow
on:
  pull_request:
    paths:
      - '**.md'
      - '**.rst'
  pull_request_review:
    types: [submitted]
  workflow_call:

env:
  DOCS_TEAM: 'pconrad-sfdo'

jobs:
  docs_review_needed:
    runs-on: ubuntu-latest
    steps:
      - name: Document review needed (RST/MD)
        id: docs-filetypes-review-needed
        if: !github.event.pull_request.draft &&
            !contains(github.event.issue.labels.*.name, 'doc review needed') &&
            !contains(github.event.pull_request.requested_reviewers.*.login, env.DOCS_TEAM) &&
        uses: SFDO-Tooling/github-script@v4
        with:
          script: |
            github.pulls.requestReviewers({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: ["${process.env.DOCS_TEAM}"],
            });

            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['doc review needed'],
            });

            core.setFailed('PR requires doc review.');
  docs_reviewed:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved' &&
        github.event.review.user.login == env.DOCS_TEAM &&
    steps:
      - name: Remove review needed label
        id: rm-docs-review-label
        if: contains(github.event.issue.labels.*.name, 'doc review needed')
        uses: SFDO-Tooling/github-script@v4
        with:
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'doc review needed',
            });
      - name: Doc review complete
        id: docs-reviewed
        run: exit 0
