name: SFDO-Tooling Pre-commit Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version used by pre-commit."
        required: false
        type: string
        default: 3.10

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python ${{ inputs.python-version }}
        id: py
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
      - name: pre-commit cache
        id: pc_cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.py.outputs.python-version }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.py.outputs.python-version }}-pre-commit-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pre-commit
      - name: Install pre-commit
        if: steps.pc_cache.outputs.cache-hit != 'true'
        run: |
          pre-commit install --install-hooks
      - name: Run pre-commit on changed files
        run: |
          git fetch --depth=1 --no-tags origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git fetch --depth=1 --no-tags origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          pre-commit run --files $(git diff --diff-filter=d --name-only $GITHUB_BASE_REF..$GITHUB_HEAD_REF)
