name: Update Python Dependencies

on:
    workflow_call:
        inputs:
            python-version:
                description: "Python version used by pip-tools."
                required: false
                type: string
                default: '3.10'

jobs:
    update_dependencies:
        runs-on: sfdc-ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
              with:
                  ref: main
                  fetch-depth: 0
            - name: Set up Python ${{ inputs.python-version }}
              id: py
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ inputs.python-version }}
                  cache: pip
                  cache-dependency-path: "requirements/*.txt"
            - name: Update dependencies
              run: |
                  pip install pip-tools
                  make update-deps
            - name: Commit changes and open PR
              run: |
                  export WEEK="w$(date +%V)"
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git switch -c "dependency-updates-$WEEK"
                  git add requirements/*.txt 
                  git commit -m "$WEEK dependency updates (automated)"
                  git push origin "dependency-updates-$WEEK"
            - env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh pr create --fill --label 'auto-pr,dependencies'
